[http://compliance_audit]
disabled = 0
index = automation_local_user_group_audit
indexes = automation_local_user_group_audit
sourcetype = user_audit_signoff
token = 36697550-b07a-42d5-a5a0-e3d720a610be
