[http://compliance_audit]
disabled = 0
host = chongs-MacBook-Air.local
index = automation_local_user_group_audit
indexes = automation_local_user_group_audit
sourcetype = user_audit_signoff
token = 94567e0d-0e2d-491f-ae98-95ce35320d86
