[launcher]
author=CJ
description=Local & Group Users Audit Dashboard for different systems
version=1.0.0

[ui]
is_visible=1
label=Compliance - Local & Group Users Audit Dashboard

[package]
id=compliance_account_review
check_for_updates=0

[hec_config]
token = 94567e0d-0e2d-491f-ae98-95ce35320d86
url   = http://localhost:8088/services/collector/event