[launcher]
author=CJ
description=Asset-level review of local users and groups, and account-level review of individual account access.
version=1.0.0

[ui]
is_visible=1
label=Asset & Account Compliance Review

[package]
id=compliance_account_review
check_for_updates=0

[hec_config]
token = 36697550-b07a-42d5-a5a0-e3d720a610be
url   = http://localhost:8088/services/collector/event