[launcher]
author=CJ
description=Local & Group Users Audit Dashboard for different systems
version=1.0.0

[ui]
is_visible=1
label=Compliance - Local & Group Users Audit Dashboard

[package]
id=compliance_audit_users_app
check_for_updates=0
  